<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SanPhamSeeder extends Seeder
{
    public function run()
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->truncate();

        DB::table('san_phams')->insert([
            [
                'ten_san_pham'            => 'Áo Thun Nam Tay Ngắn In Chữ Sarah Baker',
                'slug_san_pham'           => Str::slug('Áo Thun Nam Tay Ngắn In Chữ Sarah Baker'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211ATA4132505/4e3380e5-791e-4336-9b75-94287012d044.jpg,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEE0MTMyNTA1LzQyYTUwOGE4LTgyNjctNDBhNC04NmE1LTkyYzk1NGMwNTE3OF9BN0IyMTBGOUJGRDVEMjRBRDQyQTczRkM3MDk2MzhFQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEE0MTMyNTA1LzhkYWRkM2E2LTg2NzUtNGU3YS1hZjgyLTczM2ZmMWZjM2UwYV9BMTE4NDAwQjQzOEYwOTcyNUEzQzk5MTNCNjIwNEUyNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEE0MTMyNTA1LzVhMmEzNDVmLWQ2NWEtNGJmMy1hOWQwLWE0NjQ5MmI0M2Q0MV9CRTVGRDY2MDM4QzdERDlCNDJGMjAxM0EwQzk0Qzg3Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEE0MTMyNTA1LzRlMzM4MGU1LTc5MWUtNDMzNi05Yjc1LTk0Mjg3MDEyZDA0NF8zQkYzM0QzQ0NDRDJFRTBFNjgxNkM5NzU0OTM4NkU1Ri5qcGc1',
                'mo_ta'                   => '- Tên sản phẩm: Áo Thun Nam Tay Ngắn In Chữ Sarah Baker
                                            - Độ tuổi: > 13 tuổi
                                            - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => 169000,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Nam Tay Ngắn In Chữ Werby Nhed',
                'slug_san_pham'           => Str::slug('Áo Thun Nam Tay Ngắn In Chữ Werby Nhed'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209ATA0671701/3af609f0-8ab6-4d4d-b489-464374f92db2.jpg,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlBVEEwNjcxNzAxLzBhNzI4YWZkLWE4ZjMtNDU2Yi1hOGI4LTM4NDJhMWViNDY1ZV84NjkxOTVEODVERERFQjc5Rjk3NjgzOTg3NDlDRDZGNi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlBVEEwNjcxNzAxLzNhZjYwOWYwLThhYjYtNGQ0ZC1iNDg5LTQ2NDM3NGY5MmRiMl9CRTZENDE4MjI4MUQwQkZDODkyMDNBRTRFNjJBNkM4OC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlBVEEwNjcxNzAxLzVlZDYyMWYwLTUyODAtNDA2Yy04ZGFhLWIwOTgzZDNlYmY0MV9BNjA2OEU4NDZFMDY4N0VDQzZFODM1OTA1NjY5Rjg0RS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlBVEEwNjcxNzAxLzE2ZjUxNGNmLWI4NmUtNGUwNi1iZmI5LWRmZDlkZTA0MzUxYV8zNzQwQjI4MEIxQUM2MjBERURENzUyNjNCNzdDN0NBMC5qcGc1',
                'mo_ta'                   => '- Tên sản phẩm: Áo Thun Nam Tay Ngắn In Chữ Sarah Baker
                                            - Độ tuổi: > 13 tuổi
                                            - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 189000,
                'gia_khuyen_mai'          => 99000,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Chữ Greative',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Chữ Greative'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATA0670901/3dedbe52-ed87-47fd-a019-f447b7047092.jpg,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEEwNjcxNTAxLzNiOGU5MzQ3LWQ2ZTktNDA3OS04ODk4LTY3MDY5ZWE3MjdkOF81NDdGOTAxMTNENzQxNjY1ODVFNzAxRTA0RjJDOTE0Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEEwNjcxNTAxL2M3NmUxNzI4LTQwNWMtNDg1NC1hMTdmLTJiOWI4NDU1MDNiOV85N0M0Rjg3ODZGOUQ0QjFCMkE3MkYzMEE4MzU4NTU1Qi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEEwNjcxNTAxLzQ3ZTRmNWVhLThkZjUtNDI3ZC05ZWE5LTBlNzJiYjRjMjgxYl84Mjk1QTEzREZCRERBQTVCN0RBOEY0NkU5RUVBMUMwQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEEwNjcxNTAxLzgwMWNiZjU0LTc1NzMtNDVjMS1hNDVlLTM1MWE0ZGMyNzc2MV9CM0E1Q0FFRkQ2RERBODI2RjVBMDc2NzY2MDlCRTUxQi5qcGc1',
                'mo_ta'                   => ' - Tên sản phẩm: Áo Thun Tay Ngắn In Chữ GREATIVE
                                            - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.
                                            - Chất liệu: Vải thun',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => 105000,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Polo Nam Phối Màu Túi',
                'slug_san_pham'           => Str::slug('Áo Polo Nam Phối Màu Túi'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIwNjI5MDA3MC8xOTNiMzI2ZC05ZjdmLTQ4ZmItODBhYi1jNThlMWI2YWQ2YzFfMDlDOTY5RTJCQjNCMzdBNTIwQUNENzhENDUwNDE5QjcuanBn0,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBVEE5MDQwODAxLzRkNzNkNTM2LTNlZDMtNGM2Mi04MDAyLTBhOWUxYTJmY2NkOF9FQUU2NDIzRTU5REY5N0E3NEI3N0JDNjY0MUI1MDI2Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBVEE5MDQwODAxL2EyMmU4ZjZlLTY1NzctNDJmMC05NTdjLTI3NWI2NTVkNWFjZF9GNjYwOTVCMzUyREU3MkE1NTBBMjdGNUQ2OEMyQzg5OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBVEE5MDQwODAxL2EyMmU4ZjZlLTY1NzctNDJmMC05NTdjLTI3NWI2NTVkNWFjZF9GNjYwOTVCMzUyREU3MkE1NTBBMjdGNUQ2OEMyQzg5OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBVEE5MDQwODAxL2MyMDc0NmZkLWQxY2YtNDlmNy04NDkzLTZjMjk3NmY5NGRmYl9CMjUyNkJCNEM4RTVDQUFBQURBMTk2MDJDRUU0N0Q3RS5qcGc1',
                'mo_ta'                   => 'Áo polo là item được nhiều người chọn làm phong cách thời trang riêng bởi độ lịch lãm, thoải mái mà món đồ này mang lại. Đồng thời áo polo còn dễ dàng mix với nhiều món đồ',
                'gia_ban'                 => 275000,
                'gia_khuyen_mai'          => 245000,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Nam Phối Màu Cổ Và Tay',
                'slug_san_pham'           => Str::slug('Áo Polo Nam Phối Màu Cổ Và Tay'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJQVEFGTUYxNjAxLzUwYjI2YTVlLTRlYWYtNGYwZC1hNGE2LTRiODIwN2FhYWEzYV9CM0Q2MjA2MDg1NDUyQUZGNTBBMkFBQTNBRDMyMTc0Ni5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJQVEFGTUYxNjAxLzRjZjUzNTEzLTIwNmItNGNjYS1iNmRlLTczMWFhZDhiY2Q4ZV80ODFDRjEzNTIxQTAzOTA4RTYzMDcxQ0FCRTQzNjI3Mi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJQVEFGTUYxNjAxL2ZhZGM0ZDU0LTMxOWYtNGUwNi1hOThjLWRkNzY0ZjYzN2IwMl80MjZGMjRBQTNFNkJBRDBCNjA3QjJCOEQzNzdFODc2RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJQVEFGTUYxNjAxLzQzY2M4M2M4LWIzYWEtNDBmNy1iNjA5LWYzNjczNTk5OGQ5M183ODZGNEQ1QzIxNzhFREExREM2QkFCREYwOTYwMDc1RS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJQVEFGTUYxNjAxL2M1MmU2OTI4LTgxZDctNDM4Yy05OWYxLTE3NmY2YjQ4Y2UxZV9ERTY2NTQzOEUwODM4NjU1QjU1Qjk3RkEwM0Y4Nzc5Ri5qcGc1',
                    'mo_ta'               => '- Tên sản phẩm: Áo Polo Nam Phối Màu Cổ Và Tay
                                              - Độ tuổi: > 14 tuổi
                                            - Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 269000,
                'gia_khuyen_mai'          => 119000,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Nam In Hình Mặt Cười',
                'slug_san_pham'           => Str::slug('Áo Polo Nam In Hình Mặt Cười'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207ATA5360401/2afd93c4-b593-4d52-8744-2ca0475cb455.jpg,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEE1MzYyNDAxLzVlOTMyOTE2LTgwNDAtNDgyNC1hZDc4LTNiNDVmYTY1NWM3Y19DQjZBQTlDQjM3MUE5QzdBMTk0NDE0NzhCODYyQ0U0MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEE1MzYyNDAxL2VmYWQ4Yzc0LTYwYzctNGE5Ny1hYzNhLTc1NzcxYTY5MGUzZl9FMkUyRTU4NTZFNUM0NTJEOEZDMzI5RDJFNjgzRTY3MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEE1MzYyNDAxLzc1MTNjOGUzLTdhNmYtNDRhZi1iMWFkLWJmOGU4ZjdjZjdhZl81QUVENjAxOTg0Q0M2RjA2NTRFMTY2MEZEMEI0RkI2Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATA5362401/d5b94151-2862-428a-ab2b-ddf28345045f.jpg',
                'mo_ta'                   => 'Áo polo là item được nhiều phái mạnh chọn làm phong cách thời trang riêng bởi độ lịch lãm, thoải mái mà món đồ này mang lại.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => 260000,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sơ Mi Nam Tay Ngắn Giấu Túi',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nam Tay Ngắn Giấu Túi'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhBU0E2ODIwODAxLzY5MjhiMzNmLWQyY2QtNGJjMi1iYzc4LWJiNmVhN2M3OGY3YV8yOEM0OENGMzY5MTk5MTBERjU0QkQ0QUFEMkQyNDMzRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhBU0E2ODIwODAxL2UxZmFmM2VkLTlkZDUtNDdiOC04ZTU1LWQyNGQ0ZTI1YjI3Y182QTM1RUZBRkFDNTJGNTkxNjU3RDVGNzQ3RDFCNzhCQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhBU0E2ODIwODAxLzVjY2ZlNjFiLWQxMTktNGY2Yy1hYjE2LWRmMmFlYzM2YzE4OV8xOEI2RjNFNDY5MTJGOUI2M0UwNzQ1M0VCRkJDRUQ1Qi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhBU0E2ODIwODAxLzhkZWM3NGNhLTlmOWYtNDdjNS05NzFlLWRkMGMyMWJmZmE0Yl80NTBBOENCQUVERjA4QzVDNzk2MzQ0MDk4NzVBRDNDMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhBU0E2ODIwODAxLzAyNGQ3NzM1LTYyYWYtNDgwOC1iZGFmLThkOTE4N2JkNWIyMl9BMjgwQUIzNjNFQzVCRDIwQ0M2NTVBMjIwNjdDRTM5MS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => 79000,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Nam Tay Ngắn Túi Nắp',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nam Tay Ngắn Túi Nắp'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU0FGTUYxMTAxL2U2ZGQzYTUyLThkZGYtNDhjZi04ODM2LTgxZDhlYjU2MDljZl9BOTA0MzQ3RUFFRDA4RkQ2QkQyODVCQTRFRDk0NThCMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU0FGTUYxMTAxLzBhMGRkYWZiLWQ5MTEtNGQ5ZC05YTQ1LTQwYWZlZDQ4ODRlZl9DOUNBNjg1OUM4OEI1MDNEMjNCODVDQTZFNjM0OUI5Mi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU0FGTUYxMTAxLzBhMGRkYWZiLWQ5MTEtNGQ5ZC05YTQ1LTQwYWZlZDQ4ODRlZl9DOUNBNjg1OUM4OEI1MDNEMjNCODVDQTZFNjM0OUI5Mi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU0FGTUYxMTAxL2M0YzdhZjg2LWZiNTEtNGUzMS1iNDRjLTM5ZjAwZjZhY2M3OV85OEYwODU3NDE2NDU0OEI1NTA3NjU3RkMzMUI5QzA3Ni5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU0FGTUYxMTAxLzAwOThjOTkxLWE2NmItNGI3Zi1hYTE2LWZlMWQxYjBlYjg0ZV8wRUY5RTNEM0MxNDhFQkZCN0M1OTRDOTEzQzIyQUZCNC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => 205000,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Sơ Mi Nam Tay Dài Sọc',
                'slug_san_pham'           => Str::slug('Sơ Mi Nam Tay Dài Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRBU0FGTUYwNDAxL2JiYWE3NzA1LTEyZTMtNDA4Yi04MWVhLTVhMDNjNzY1YmVkY19DMUUxNDg0RjBCMEEwMDU1MTNGQjcyQ0MyRDc4ODBEQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRBU0FGTUYwNDAxL2I4N2ZhZWE3LWJlNTUtNGE3Zi05YjY5LThiMzg4ZWExZjY1N19BNTNBMTM0NzM2NkU4QjczRkUzQTczNjcyMzM3REY5My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRBU0FGTUYwNDAxLzVjMmQxYTc2LWI0ZWEtNDdmNi05NmNmLWZmNmM2YTA5NDlkYV9FRjNCMTBEQkRGMjExOUFFREYzMUVFQ0Y5QzRDQzI4Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRBU0FGTUYwNDAxLzUzOTIxNzBhLTE1OGYtNGE5Ny1hYWI4LTk5MmRiYWQ2N2QzYl83QTEyRTc5RTcwRjRERTY3MEI1OURDNkQxMTFGRUJFRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRBU0FGTUYwNDAxL2I2ODBmMDE2LTA4MjEtNDAxMS1hMDM0LWRhOGUyYjc5YTdlYV85MTZCNkJGM0JBNjRFRTI3MDE4RENERDY1REZGMjg5NC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 249000,
                'gia_khuyen_mai'          => 159000,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Jeans Nam Đen Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Đen Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRSkE4MDUxMTAxLzhjYzEyNjM1LWM2YjAtNDI2YS05Y2IwLTdhY2Y1MTlmZWJiNl8yOTM1MTU1OTMxRkEyMTk3MjNENzcxNzFENjU3QTBBMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRSkE4MDUxMTAxLzQxMTI5YWNlLWM3NGMtNDQ2Mi1iMDM4LTkyY2Q1ZTk5MWU0OV84RDM4NjlFQTlCNkQzNUU5MTI0RkUwNzAyN0Q1RDVGNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRSkE4MDUxMTAxLzViMDFlN2Q0LWExOTItNGE5ZS04OWQ2LWViNzAxNzM5NzQ2ZV8yMDczNkY0ODU5Rjc4RDhBQjNCQ0QzQzM2MkI4N0IzNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRSkE4MDUxMTAxL2MyMDEwYzUzLTZlMjctNDhjYy05MGU0LTIyMDhjNzhhZWFiOF85RjkwM0M3MjA0NEVEN0QwNTA1M0VCMEMyRUU2MDIwMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRSkE4MDUxMTAxLzViMDFlN2Q0LWExOTItNGE5ZS04OWQ2LWViNzAxNzM5NzQ2ZV8yMDczNkY0ODU5Rjc4RDhBQjNCQ0QzQzM2MkI4N0IzNy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => 275000,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],
            //11
            [
                'ten_san_pham'            => 'Quần Jeans Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxLzkxZGY5MGYwLWNjYjYtNDIzNy05ZGRmLWY5ZjgwODUyZGI0Y18zQkU2RUI3MjA1MTdCRjEzRTBEQzRFRDQzOEYyMUY1RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxLzg5MzM0NjI4LWM5MmEtNDBmNi04ZWQxLWI2MGUwYzY3ZDI3Yl9EQjc4MzUwN0Y1NjkyMkM3NUVBOURDNTk0NEExNTJDRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2E2YmJmMGEzLWE3YWItNDNlMC04MGZmLTFlZmU1NmQxYjM4OF9DQkQzRjMxMDk0NThBRDhGMTI1Mjg5NUQ1Mzc2MzgwRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2ZjZTdjMjEzLTcxNTktNGViZi04MGUxLWU4Nzc3MjM4YzZiMV9CMzU2RUFGNzZFQjIxNDY2NzIxNzZGNTAyQzgzMUY3MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2U1MzdhNTI4LTg0MTctNDIwMy1hOGJkLTQ0NWZjOGM4NzcxMF83RjI3MzlGMTMwREU0NjU1N0FDMzMzMTRDQzdDNkRFQy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 395000,
                'gia_khuyen_mai'          => 275000,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxLzkxZGY5MGYwLWNjYjYtNDIzNy05ZGRmLWY5ZjgwODUyZGI0Y18zQkU2RUI3MjA1MTdCRjEzRTBEQzRFRDQzOEYyMUY1RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxLzg5MzM0NjI4LWM5MmEtNDBmNi04ZWQxLWI2MGUwYzY3ZDI3Yl9EQjc4MzUwN0Y1NjkyMkM3NUVBOURDNTk0NEExNTJDRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2E2YmJmMGEzLWE3YWItNDNlMC04MGZmLTFlZmU1NmQxYjM4OF9DQkQzRjMxMDk0NThBRDhGMTI1Mjg5NUQ1Mzc2MzgwRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2ZjZTdjMjEzLTcxNTktNGViZi04MGUxLWU4Nzc3MjM4YzZiMV9CMzU2RUFGNzZFQjIxNDY2NzIxNzZGNTAyQzgzMUY3MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRSkE1MTcyMzAxL2U1MzdhNTI4LTg0MTctNDIwMy1hOGJkLTQ0NWZjOGM4NzcxMF83RjI3MzlGMTMwREU0NjU1N0FDMzMzMTRDQzdDNkRFQy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 395000,
                'gia_khuyen_mai'          => 275000,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Kaki Nam Dài Trơn',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Dài Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJRSkE5MDMwNTAxL2RlZDg0NmE5LTE5NDUtNGM2MS1hZDEwLTdhZjY2ZmIyZmUxYV8yOTU2OTc4NzlFMzU1RkY0QjJGNDE4MDNCQUUwRjA3Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJRSkE5MDMwNTAxLzg2MDk0NGI2LTg0MmEtNGIwZS05OTdmLTE5MmMwZmZjYzA2M181QTQ1RDE1MDQwMkYwQzdFMENBNjMwMDk0ODJEQzdFNi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJRSkE5MDMwNTAxLzEyODA5MzZlLWMyYmMtNGI1Ny1hN2ZlLWNhZDZlNTlhOTc2MV80MDU5QUU2RjA2MDM2NUNDNEY4N0FDMzdERUUwRjIyQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJRSkE5MDMwNTAxLzQ0MThjOWM2LTI1ZmQtNDU2NC04ZGU2LTQxNjI4ZWE4YzkxOV9DNzNDNjE0MDg3RDk5NUQ3M0RDQTE3QzZBMkJBREMwQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJRSkE5MDMwNTAxL2RkY2MyMTA1LTUzMDYtNGExNi1hMWM2LTU2ZTQ5YjYyOGEzYV83QTFDQjRGMjA2NzZCQTlBMDg4MDlDRjMzNTlGOEIwQi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 325000,
                'gia_khuyen_mai'          => 235000,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Kaki Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E5MTUxODAxLzk5ZTEyYWY4LTQ3MmUtNDk1ZS05OWI2LTliODNkNjk5NzY4YV85MkIwNjAyRjNFN0QyODQzRkQyQThDRkNENURCQzhBOC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E5MTUxODAxL2U2N2ZhMzc4LTljOGYtNDUyMi1hZGRkLTA1ZDhkMDcwMmRmMV9ENjdEOUU1Q0JBQTBEOTlERTE1RUU1OUNGOUQxNzg4RS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E5MTUxODAxLzk5NzczNDRiLWFhOGUtNGJhYS04NjUyLTRlZTJhOTNiZWE0NF82RUYyOTlDNDE3Njk4NDhCMjQ1MjE0N0E4MjQzREMxOC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E5MTUxODAxLzMxNmYzYWZlLTA4YjEtNDYyNC1hNzYyLTFjODViMDZjMDk3Yl85QjQxMUQ0RUY3NTZFMjU2MjEwQjFGNzkwQTJCNTQ1My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E5MTUxODAxLzEyY2Q0NzhkLWIxNTQtNGU3Mi1hODU4LTc4MDg3YWI3ZDc4Nl8xRDI4NTNEMkQ1OThCNTA1QkRFQTVFMkYzQzMxMEQ3Ny5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 325000,
                'gia_khuyen_mai'          => 205000,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Kaki Nam Dài Mac Fm',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Dài Mac Fm'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E1ODYwNDAxLzg3NGY2NzMzLTQxNzItNDk4Mi04MTNmLWI4YmM0ZTI1Mjc3MF9FMEI1NTgxN0FDQ0RGOTBCOUQxMjgzQUZGRkFDNkRGRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E1ODYwNDAxLzhmNmQ4ODE5LTljN2MtNGZjNS05M2I3LWM5MTU1OGUyYWMyNl9DODJCQkNGNkVBOUVCRkMyNzNFRUFDQjI5QzA1N0U0My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E1ODYwNDAxL2UwZmZhYmNmLTZlYjgtNGEyZi04MDZjLTAxN2Y1NzY1MjkxN183N0FGODg0MjZCQ0YyODgwMUY0MjQxOEI0NkVGQUI2My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E1ODYwNDAxLzQ3ZGVkM2E4LTJlYjEtNDBhNi1iYzExLTZjMGJiY2FjNmFiMl9FRDlDQ0VBNTM3NjgyMjc5NDk4NkRGQ0IzN0U1RDREQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRS0E1ODYwNDAxLzQwNmE3YjU2LTYxYjMtNDdkYS05Mjc1LTE1NTI5ZWEyNTgxZl9DNjk5Nzc2MjU1NkNFMkREN0M1QjYyRkNCNDI0OTg2Ny5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 295000,
                'gia_khuyen_mai'          => 205000,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Short Kaki Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Short Kaki Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVTS0E5MTUxOTAxL2NhMjRhMjA3LTlkMzMtNDRjYi1iZmZiLTYxNGIwOGQ1N2ZhNl8yRkUxNkRBQUQ1RTNEQTdGNEE5NjlCQzhGQ0I4ODVGOS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVTS0E5MTUxOTAxLzRlODllMjI5LWY5YTgtNDA2OS05MGM4LWZmZjY2NWUzNjRlOV9FOTUyM0I4NzA0QUJENDY4M0U0MTk3OEI5M0UwRDBCMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVTS0E5MTUxOTAxL2UwZTMxMWY1LTVkNDYtNDAxYi04YTU2LWZjYjMyNzkyYTlhZV9FNTJFMDZCRUQzMjNBRDFGM0I0Qzk5NzZCQzhDODgwMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVTS0E5MTUxOTAxL2UwZTMxMWY1LTVkNDYtNDAxYi04YTU2LWZjYjMyNzkyYTlhZV9FNTJFMDZCRUQzMjNBRDFGM0I0Qzk5NzZCQzhDODgwMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVTS0E5MTUxOTAxL2ZjOTZiODExLThmZGUtNGI4Mi04Mjc0LTBjNWE5YzkxZTExNV81OEQzNkY1Q0U1RkFGODkxQTAyMkM3MDYyOTI5MDcwMS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 175000,
                'gia_khuyen_mai'          => 25000,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Short Tổ Ong Lưng Thun 2 Túi Hộp',
                'slug_san_pham'           => Str::slug('Quần Short Tổ Ong Lưng Thun 2 Túi Hộp'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdTVEE5MTUyOTAxLzRiZjdiMmRjLTA0YjgtNDUyZC04N2IyLWZhOTU3OTZjZjVmZF9DRDZBREEyMDlCOUM1N0YyQ0VCNUQwNDhFQzJGODJCNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdTVEE5MTUyOTAxLzYwMTBlM2YyLWZiNGEtNGY2OS1iZTExLWQ4NDdlOTM5OTg5NF82MjQwQzVDODIxQjA3MTE4RUU1RTg5MUQzQ0U4RDJGQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdTVEE5MTUyOTAxLzJlNDBlMTlkLTU4NDEtNDRlNy05ODFlLWU5ODY3NjJjMDEwZl9GMzgxMzFCQUUyODlEODdGRTNFOEU2QzMzOTQ2RDBDNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdTVEE5MTUyOTAxLzQzMmMzNWQ5LTRjZTYtNGQ5YS04ZTdjLTE0ZmQ3MWM1ZmY3MF8zNTEwMTJENTRGRDcxQ0I4MEY4MzhFQTM3OEQ4MUIwNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdTVEE5MTUyOTAxLzY1MDMxZTA2LTBmZWQtNDkxZC04MjkwLWFmMzUwZGJjZjNjYV81NDBCOTg4MUFBNkU5RjAxNUE3NjYzNDg3NjJDNjQxNi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => 165000,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Short Đũi Lưng Thun Rút Dây',
                'slug_san_pham'           => Str::slug('Quần Short Đũi Lưng Thun Rút Dây'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlRS0E5MTUyMzAxLzcyNjkxZjVmLThiMDgtNDk1ZC1iN2I3LTUxYmNjMDg1Mzg2Yl9CNkY3QjJFNjNEOTNFNkYwMDE0QjhEMUIwMzAwMUI2Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlRS0E5MTUyMzAxL2UxNzBkNjVkLWVhY2EtNDM3OC04MzcyLWM2NmYyZjQ3YTAxN18yMzNDN0I3NTExRjgwNTc2QzFEODUxNDQ3MzhBOUE0MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlRS0E5MTUyMzAxLzJkYzBlMzdlLTAwYTEtNGQ1NS05ZDk5LThjOWZiZDk2ZjIyM19DQTI5NkY0OUY5MDlDRUE0OUY5RTE3Q0VDNUFDMzVGQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlRS0E5MTUyMzAxLzQ1M2M0YjY2LTBjNDUtNDQwMy1iNTQxLWU3YTgyNjUyZmQwNF9EM0NCNDNFRkQ5NkExQTU1QTc1MzFGMTA4MzE5NTNCMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlRS0E5MTUyMzAxLzk3MTIzODg2LWRmN2MtNDRjMS1hM2ZjLTg2ZWVlZDdkZGI4ZF9CN0JGNTcwQjQ0OUJEN0NENTk0NzczMjA2ODlFMDA0Ny5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 129000,
                'gia_khuyen_mai'          => 69000,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Feel No Toks',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Feel No Toks'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzM0N2U3MGE4LTE4YzktNGFlYS1iZWQ2LWZlNDE0ZGQ2ODU3MV9GRUQxRjI1MkFEQzgxRjREM0EyN0E2NkRFQkRCRDFERi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyL2JmN2FkM2JmLTVjZTUtNGQyMS04MGE5LWViMjFkOWJiZWEzNV8zOUJEQjE3RTBFQzk3NDlDMjZBRTU2MDQ5NEJCRUUwRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzBmNDEyZGY0LTdkNmEtNDkxZS04ODQ0LWU1NTI4OTg5ZDU0MF8zREMwQTM2MDJGRjkwREUzQTAzOUFGRjMwQjA1NzQ4Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzM0ZTllMjg4LWM3Y2UtNGMxYy04MTU1LWNjMGUwNmU4ZmJmNF9ENkJERUVFNzc4OTlCQzdEQzQ2MTZFNTk0MTcxMkQwRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzI4NTEzNzkxLWFhYmYtNGQ1Ny04ZDdmLTNkY2EyNDJlYWE1NF9FNjUzQjE4ODYwMkYzM0JDOTlBRDUyRjFDOTM0RDc5Mi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => 265000,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Bomber Nam Trơn',
                'slug_san_pham'           => Str::slug('Áo Khoác Bomber Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFLS0FGTUYzMDAyLzAwZWQ2NjE3LTUxMGYtNGUyNS1hZjVjLWMyOGY2YjEyMzRkNF9GNzg3MjQ3REQzQjVGNTVFNzIxNUU0MkRDRDQxMjg0Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFLS0FGTUYzMDAyL2JmNDAxY2MwLTZkMzMtNDM0Yy1iZWUzLWYwODk3ZGU1YTJjNV83NENCRkJFRTFFNjA0NTlDQTgxQTEzNTZCMkFDN0Y5Mi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFLS0FGTUYzMDAyLzQwZGQ2ZjM4LTA0MDAtNDQxMS1iNTc0LTc1YjUxYzZjYTU4MF85MDk4Rjk5MEExOTRBMjg2OEIwNzM5NjNCNURCRjE0MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFLS0FGTUYzMDAyL2I4MmRiMmI0LTI1NzMtNGI3ZC1iOWYyLTFlNWZhYWE3YTk0MV84MzIzODE1QkEwMkM3MTc4MjQ1QzU5NDE4OUNFMkU3OC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFLS0FGTUYzMDAyLzgyN2FlODZlLTg1NjgtNDQ1NC1iZWFjLWEzNTZkZTYxYmM2MV9BRjhGRjk2NTYyMzg2NEY4NjBFNTg0MUIyOTZCRkQ0MC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 395000,
                'gia_khuyen_mai'          => 245000,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Gió Nam Phối Sọc',
                'slug_san_pham'           => Str::slug('Áo Khoác Gió Nam Phối Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJLS0FGTUYwMjAxLzE1YzllMzFiLTQ1MjktNDdmZC1iODQxLWY0NTIwYTdmMmIyNV85OUZDREE3RkZEOUY2MjRFOEMxRjc0RjVCRjY5NTA5OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJLS0FGTUYwMjAxL2RhNWUwNmVhLTdkNTAtNDE0MS1iZTliLTk1YzZhNmQ5YWFkYl9BQTU1N0YyQTYwOUY3NTJFMTRGQ0QwRjJBNUVEMEI1Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJLS0FGTUYwMjAxLzM2NTU1YzllLTkwZjgtNDE3ZC05OTc0LTY2ZDE1OGMzYzE5NV9DQ0FCODFCNEVDRThENTQ2RTM0QTFBNUFBQkZCMjEyNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJLS0FGTUYwMjAxLzM5YmI4NDAxLWRkZTItNDg2Ny1hODVjLTExYTc3ODFhODk1YV83RTRFMDIxN0QyMDgzMzVBRDNCQjI5NEFEOUQ0Q0Y2MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJLS0FGTUYwMjAxLzNkOTk3ZjBhLTQ5YTQtNDBhNS05MDFiLTQwNGE2MmM5YWM2OF80MEZBNTU2RDA4QTkzNkMyRDNGMzVBOEVCMjA4NzBDMC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 475000,
                'gia_khuyen_mai'          => 475000,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Feel No Toks',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Feel No Toks'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzM0N2U3MGE4LTE4YzktNGFlYS1iZWQ2LWZlNDE0ZGQ2ODU3MV9GRUQxRjI1MkFEQzgxRjREM0EyN0E2NkRFQkRCRDFERi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyL2JmN2FkM2JmLTVjZTUtNGQyMS04MGE5LWViMjFkOWJiZWEzNV8zOUJEQjE3RTBFQzk3NDlDMjZBRTU2MDQ5NEJCRUUwRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzBmNDEyZGY0LTdkNmEtNDkxZS04ODQ0LWU1NTI4OTg5ZDU0MF8zREMwQTM2MDJGRjkwREUzQTAzOUFGRjMwQjA1NzQ4Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzM0ZTllMjg4LWM3Y2UtNGMxYy04MTU1LWNjMGUwNmU4ZmJmNF9ENkJERUVFNzc4OTlCQzdEQzQ2MTZFNTk0MTcxMkQwRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQxOTAyLzI4NTEzNzkxLWFhYmYtNGQ1Ny04ZDdmLTNkY2EyNDJlYWE1NF9FNjUzQjE4ODYwMkYzM0JDOTlBRDUyRjFDOTM0RDc5Mi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => 235000,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],
            //22
            [
                'ten_san_pham'            => 'Áo Sweater Nam Thêu Chữ Goff',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam Thêu Chữ Goff'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyMTAyL2Q2Njg4Y2IxLWVkZTMtNDkxMy1hOGY0LTZlYmQyNjZiOGRhZl8zMEI3QjE1Rjk4OUJDOTgwNTZFMUNCMkI4NjYxMThDRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyMTAyLzNjZGM3NTk0LTBiMTUtNDVhYS1hZGExLWY0ZTcwYjI2NDZjM18zM0YxMzBDNjAxMjNDOTVERkE5QTNEMjE4OEZDODNDRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyMTAyLzUyMTE5MzNiLTUwNjgtNGJmZC04OGU4LTEwMGE2NWNlZmRkMl9GRDMyN0U4QTQ4NjkyODQ3RTQyMDgyQThFQjRBOUNGMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyMTAyL2EwNDIyYjk5LTI5ZDgtNDI0Ni1iNTVjLWQzYmI4ZjI0NDJlNl9BNkREQjM5RDlBNEIzQ0MxMjQ0MkJDQURFMjgyMDZBQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyMTAyL2NiYTcxZGI0LWM0MmUtNGEyNS1hZjRlLTFlODRjNGE2YmIwZl81MzZERkM0MTVENTk5Q0JENzNBQjFBMTE1M0U1RDJFRS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => 235000,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Bring Together',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Bring Together'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyODA2L2QzYTRiOGM1LTg3YzEtNDE3NC05MDE1LWVjZTVkMGFjZmE4Zl8xMDY2NEVDQjVCRUZFMDAzMzdGQzI2OTk3NDFFMzQ2MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyODA2LzM5N2E2OWM5LWZhNmUtNGFjOC1hMmZmLWNlMzg2NjNjNmE3Y19DNTJFMTE1RThGMzFFRDM3M0I5ODUxODkxRTc3QTcxNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyODA2LzU3YTUyYjFmLTIwYjItNGMwYS1iZWUwLTlkOWU0NDQxM2NmNl9BNUI4M0RCRUQ1N0ZBQ0M0QUNEMTVGNUVCNkNDODJDNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyODA2LzRjNDY5Y2U2LTFkNDgtNDQ4My1hZWYzLTdlOTk2MjA1ZTYzMl8yQzIyRjNGOUFDQThBQjJCOTY5OUFGMjA4RjlFRTM0OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBUkE1NjQyODA2L2EzMGRjZWEwLTgzZTctNDNmYy05YWJkLWM3ZTdiMGEzN2Q2ZV9EQURFQTMyOUM2QUZBMTcyQjJBNDU2OEM1NDlDRDJFMy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => 235000,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài 2 Sọc Ngang',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài 2 Sọc Ngang'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAxLzQ4YTM2ZDhkLTE3ZDMtNDhiZi04Yzk1LWI3N2U5NDAyYmU1Nl81Q0FGQTE0REQ2RTMyRjdFM0NDNzg2RjYzNkI5MTg2Ni5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAxL2ExY2MxMzQ3LTcwYmQtNGU0Mi05ZmMwLWRkMWQ0ODRjNjEyNV81RTUyMzkwNDAyRjVFQkJDRURFMzdGM0Y1NURCM0U3RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAxLzU3MGM5MGM3LTdlNTQtNDE1Yy1iMmUzLTg2Yjg0ZTdmOGVmYV80QTQ1MEM4RTZCRUI3NUZDNjQ2ODg1Mzc1MDMwNkY4MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAxL2E5NDY5OTBiLTNhNDgtNDcyMS04YTUyLTNkOGJkNTI5NGQ0Zl85QTYwNDMwOTcyM0JEMzkzRDI1NTAyMTY2QzU0QkEyRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAxLzZjMzVjYWUyLTUwNTYtNDQwNS1iYWI0LTYyN2U5ZTc1ZmJiZF83MEYyQjYyMkFBNUQ1QkQ0MjVGQ0ZDMEQ5ODU5RDIxNS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => 345000,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài Cổ Tròn 2 Sọc',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài Cổ Tròn 2 Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAzLzZjMTlkMjQxLWNmYjUtNGM0OC05YjA0LTY0MTAyYzVjNGMxZF80NUI4NEM1Nzg5NjgzNjEzQjZGNkQ3MzE4MjAwNzA2NC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAzLzE4YmRkZmIxLWU2ODgtNGMxYi1iMTQ5LWVmODdkNDU0ZTc1YV85ODI4NEY3MjVGOUYwMkQ0OEIzREIyREVFMEVDQkY4Qi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAzL2IyNjM2ZmM5LWU3ZTUtNDAwZC04NTNkLWI4ZWFhZGVhMmRiY183OUU3QzQ1QUUyMEZDQkVCRDAxNDY4RENBRUI1QTBEQS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAzL2JhOGM1NjMyLTNmNGQtNGI2NS1iODE3LWRlZWMyNzgxYzMxZF9BODRDNTFCNTY4ODBDMkFFMjE4RUQxRTEzQ0QxNzVEMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyNjAzLzIyMzVkZjI0LWYxNDctNGM4Zi05Y2M1LWUyMGY4YzUxODQ5N181RjI3QjAyREJDMDY3NjA4NDk0NjI0NDVCMURBRDNDNS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => 285000,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài Phối Màu',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài Phối Màu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyOTAyLzA2YjE2Mjc2LTk5OTYtNDY2ZS1hMDY2LTM1MDBiNzk1NTNjMl8xMEY5MEE4NTg3MkU1RUI5QTNBNUI0Q0VDRjZBNUE0My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyOTAyL2QwYmU4NjY1LTU4N2UtNDQ4Zi04MmI5LWM0M2MyYWIxNzdjM184NTQzNjQzQjE0QjcxMTJEMzE0RDc3NjA1RkZFOUQ0QS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyOTAyLzYzNDA0Y2YwLTkzYmMtNDVmYy1iMzI5LTI5NGY2NTQyMDk4N19DNkI5QzAxMzAzMjI2RTUyRjYzRTQ3NkJGMDJERDg5Qi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyOTAyLzViMjQyNjY0LWI5MmQtNGI3Ni1hMmQzLWRmMGM0ZDM0ZGIyNF82QjBDQUY4NDU2RTBCQUI3QjQ0NTZBQ0UxRTdGOURFNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBTEE5NjIyOTAyLzZmY2Q1NTNhLWQ2NWEtNGRlOS05YjU4LTczMWM1NzRjNWNkNl9COTU0MjM1Njk3QkQ4MzI3QjNGNEZFQkZBMDAxNzEyOS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => 255000,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Polo Đôi Phối Màu',
                'slug_san_pham'           => Str::slug('Áo Polo Đôi Phối Màu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjczMDAxL2NkNmEzMDhhLThmOWQtNDRkOC1iNmY5LTRmMDVmNjE5NGNlNF82QUUxNDZEMzdDMjU2QTJEODNBM0FCRDVDMzRGRTczRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjczMDAxLzI4NGFhMzgyLTkyNjYtNGY5Zi05MjM5LTRhMjNjYmVjMzM4OF8wRDJGRjJBNUNDMTNCQTE5RDc4MUE1NjZGQkYzNTgzNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjczMDAxLzI4NGFhMzgyLTkyNjYtNGY5Zi05MjM5LTRhMjNjYmVjMzM4OF8wRDJGRjJBNUNDMTNCQTE5RDc4MUE1NjZGQkYzNTgzNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjczMDAxL2ZiNjQ0OThmLTY0NGEtNDUzZS1hMjkyLWMxZGNmNTU0NzYyNF8wMjlENTc5NDhCRTYxOTY1RjJDMUMzNTYyOTA1M0ZDMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjczMDAxLzAzZmYxYjY2LWZlYmEtNGE5Ni05MTI5LWU1MDcxYmMyZGZkYl80QUU1QkM2QzBFQkRENkMzNDMxMkJFMzk3RkRBMjEyQy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 285000,
                'gia_khuyen_mai'          => 165000,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Đôi Phối 2 Màu',
                'slug_san_pham'           => Str::slug('Áo Polo Đôi Phối 2 Màu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjcxOTAxL2U2ODZlMzhjLTEwNjctNGEzYi04OTBlLTA5ZjEzMTU1ZDk0OV81RDE4MDU2MTU4Mjg2MzA0NDI2RUY5MUZFRTJEMEMwMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjcxOTAxL2U2ODZlMzhjLTEwNjctNGEzYi04OTBlLTA5ZjEzMTU1ZDk0OV81RDE4MDU2MTU4Mjg2MzA0NDI2RUY5MUZFRTJEMEMwMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjcxOTAxL2Y1MjlhYmEzLTVlNDEtNDY5MS1hMWQ3LWM0OGMyMzcxZmNhYV9FMjY5RUQ4NEE2MzYxRTdFQzkzNDEwNjkyMzEzNjdCNi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjcxOTAxL2Y1MjlhYmEzLTVlNDEtNDY5MS1hMWQ3LWM0OGMyMzcxZmNhYV9FMjY5RUQ4NEE2MzYxRTdFQzkzNDEwNjkyMzEzNjdCNi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBVEMwNjcxOTAxLzdiN2Q3MTc1LTdjMjYtNDRjMi1iNTA5LTkwNDhmNjRlN2Q2NF8yMDZDQ0NDNTg5MDc0RDVEOTE0NDM1NUJFNjAwQTdFMi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 285000,
                'gia_khuyen_mai'          => 135000,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Gió Có Mũ Nam Nữ',
                'slug_san_pham'           => Str::slug('Áo Khoác Gió Có Mũ Nam Nữ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlLS0M0NTg0NTgxOTAxLzJjZWMwYTljLWM5NTAtNDNkYy05NGM3LWJmZTdlYWY0N2U1OF8zNDkxODQyMTJFQjAyQzEyRkVEMjYyMUE5NTQ3REU1Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlLS0M0NTg0NTgxOTAxL2ZkYTU2NTYxLTRlNzYtNDlmOC1hOWI1LWEyN2MwYTgzM2EyMV8yMUNEMkY1OTE3QjY5RUQ2NzMyMUMxNzNGMUE4NTI1MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlLS0M0NTg0NTgxOTAxL2YzM2MzYmM3LWU5YjUtNDFhZi05NzQ4LWJhOTkyODM1NDYxOV9BQzIxNDkzMzQ3NTU2NjExMTY4MDU3NjZERjhDNEUyMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlLS0M0NTg0NTgxOTAxLzE0ZDJhNWIxLTExOTQtNDM0Ny05ZjVkLTcwMzk2MzFlNDhkYl8wNTZDQjJBNTVFNTU4MTNGRTRFMjI2MTdDRkU1NzEyMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDlLS0M0NTg0NTgxOTAxLzk3YjkwNjQ3LTAyNDktNDQ2Yy1hN2UyLTI2N2JkYjNkYzk2OF82MjUwQjQ0MTUwNEVBMzM4NkY3QjNBQjk1MUY5RDQ2Ni5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 249000,
                'gia_khuyen_mai'          => 189000,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Hình Con Trai',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Hình Con Trai'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAyLzdkZDY0MmRiLWVkMWYtNDcwMy1iYWY2LWE3YTU3MWI1ZmI2M182MEEyRERGQTU4MkJDM0NDOEM5NDJDRDg3QTU1RTA2Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAyL2YxY2NlMDVhLTVmOTAtNDgwMS04ZWYzLTNiODZhZjNjMTZkZF9CQjI2RDg2NTAxQzgxRTI5RTRBRDREOTAwMzJBNUUwMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAyL2JlMzFhYjlkLWQxMTUtNDYxYS05MzVhLTQ1MDM0YmM1MjQ2Yl9EMkZENzhBQjc3QzAxMzk0NkJFQjIyMEZBMTQzQkFGMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAyLzQ3YzI0OTRjLWMwOWYtNGIxMi1hZWQ2LWQwZDA2NzZkNGM1YV8yODFBNUZFMUM2NUZDOTEyNjc0OThBNzlFRkM2RjEzMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAyL2I3OTFhNjcwLTI0NjYtNGZlNy1iYjIxLTY3YzE4Yzc2NzA3MV8wOUVFQUIxOUI0MzUzNzk2NkU2QTY4M0VFNzU3MzlERC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => 79000,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Gấu Hồng Lotso',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Gấu Hồng Lotso'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAxL2MzMTA3YTliLTFhNmItNGQ5ZC05NTIwLTU3YjYyMzFkYjI4ZF9CN0M0NUY4Q0I3OUFDNTA0M0VGMDhGNjBGMDdDOUYwRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAxLzEwYmFmY2U0LWQ5OWMtNGE4Mi05Zjg3LWI4NzYxM2Q5MThlOF83NjIxQ0IwMTU1QjJERDdCMDk3QUYwQzk5NzQyRTFFRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAxLzc4MmE3ZjdhLTYxYzctNDQ5My04MzM1LWFlNjlhNjcyZDQyYV9DQjZDNzQ2ODc4QjUwRkIwRTI0RDFEREMxRDI3M0YyRi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAxLzc1MGVlZDU3LTI4OTUtNDQ1NS04YTY0LWRiOTE4NWE4ODdlYl81ODAzQTI2QzE4RTE2RUYxQzY1MTIxMjg5NjlGQkI2NS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNzAxL2M0OTZjNWE2LThiMjMtNDg3Ni1iOGYxLTAyMDZmYTY3NmMzY18zNDkwRDlCRDkzQ0M3MTUyMDEyMkMxQTVBMUZCOTA2Ri5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 169000,
                'gia_khuyen_mai'          => 79000,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Chữ Lucky Happy',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Chữ Lucky Happy'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNDAxLzI0YWUwOWJkLTFiODAtNGFjNS05YTg4LWEyYjQyYjRkNGUzNF9GNTQzMDBEOEUxMzdDN0VCNkNCQjI3RkRDNTQ4QzJGNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNDAxL2FhNDM5YTQxLTJhMDEtNDUxYS1iMzNkLWUzNjI2ZGEzYmRhMF80RTdGMjg1REE5NjA3QThDQ0MwQTI5Q0NEODY3OEUyNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNDAxL2EwMmZmOGQ1LTg2NDEtNDUxYS05NWVhLTllOGVmMmI5MTJkNl8yODM3OTMyODhGNjU3QjI2QTUzMzE0MjVBRTNFNUJBRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBVEM1MzYyNDAxLzhmODkzMGFmLTE4OWQtNDlmMS05Y2U5LWMxOGNkZWIxOTE3ZF8wQkIzMDNCQjc4MDFBMUUwNDVENjk0OTUyQTRBQUMzRC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 189000,
                'gia_khuyen_mai'          => 69000,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Váy Thiết Kế Dáng Xoè Cổ Khoét',
                'slug_san_pham'           => Str::slug('Váy Thiết Kế Dáng Xoè Cổ Khoét'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDZWRFVGTUYxMzAxLzBiZDMxZDczLWEyYmMtNGQ4MC1hOWU5LWU5MWJjNTBhMzQxY18xMjg0NkZFMDlDODAzQTlBOENCQzNFMzVCQTE4MzU3Qi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDZWRFVGTUYxMzAxLzFkMTZhMzBmLWMyMGItNDRlNC1iY2RhLTM4MzViYTQ1ZWE4ZV80NDE5RTkyQzYyNjY1QUE2M0FENDE4QjU4MUMxRTBDNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDZWRFVGTUYxMzAxL2M0YjM5NDgyLWNiMDMtNDE4Zi05N2M4LTJkMTY3YWM3YzJjYl9FOEFCREI2MjZFM0Y4NzA2RDcyRjhDQTE3N0JFRkE0Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDZWRFVGTUYxMzAxLzQyODNkMmU0LTRiYWUtNGZkNi1iOTM3LTAxOGM1ZWRiYmRkNl9GNjY0MUVCN0I2ODBERkM0OUY5NDZERTlGQ0EyNUVEOS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDZWRFVGTUYxMzAxLzdlMmI0Yjk0LTcyZDUtNDUxOS1hOGQ3LWUzNmRhOGQ4NTdjM18xMTg5MDZFMTlBM0M2Q0Y2QTBDRkJFOENEQjM0Q0IzMi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 345000,
                'gia_khuyen_mai'          => 159000,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Tay Bồng Cổ Sen',
                'slug_san_pham'           => Str::slug('Váy Tay Bồng Cổ Sen'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJWRFVGTUYwNzAxL2VkMjA1YjQ3LWEwNjctNDY2Yi05NGVjLTE2NzU3MjAxOWViYV9GQzY4NDQ2NUZBNTFEMjg4OTc2MDYzMUYyQTExNDc1Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJWRFVGTUYwNzAxLzQ3ZTMwYjM3LTg4NzYtNDMwMC1iMzczLTQ2NGIxNTg5MGZiNV9FMTdEMzJENDUyNzNDQjJCMzkyQzE1NzU4MTUzODdFRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJWRFVGTUYwNzAxLzQ3ZTMwYjM3LTg4NzYtNDMwMC1iMzczLTQ2NGIxNTg5MGZiNV9FMTdEMzJENDUyNzNDQjJCMzkyQzE1NzU4MTUzODdFRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJWRFVGTUYwNzAxLzVjYmYzZjI1LWE3NGItNDdjOC04ZmU2LTI5Mjk0MDc2NWZkYV81NTQ1MUQ3RTFCNDA5RTY5QUI5MEFEQzcxMjMyNTIzMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJWRFVGTUYwNzAxLzFlN2Q3MTBhLThlOGItNDMyYS1hNzBmLTZiZDAyNjMwOWQ5MV9BQjcyRDM1ODFFRkEwNjRBQTdBQTZBREI3MjZFNzVDQi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 319000,
                'gia_khuyen_mai'          => 9000,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Thiết Kế Tay Lỡ Khoét Ngực',
                'slug_san_pham'           => Str::slug('Váy Thiết Kế Tay Lỡ Khoét Ngực'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNjA1LzMxYTUxNGQ2LTU4ZTUtNDYzOC05YjU5LTI3ODdjYjM1YjAxZF8yRTY3NTAwRkNDNjNCRTM4MjU3MkU5RjE1NkUyQ0E3My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNjA1LzE0ZDgzNDdhLTBiMzEtNGZmNi1hYTM3LWQ3ZDBkOWViYTJhYV9DNTZBMUZFNUJFOUVDNkQ3MEQzMDJGQjNDMjA4OTgzOS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNjA1Lzg5NTJmOWIyLTA4YjUtNGQ2Mi1iZmJkLTdmZjA5NGYwNjEzOV83OTlBMjA2QzFERTVCOEJBODBCRDBBNzMxMjRDRTEyMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNjA1LzEyMzcxN2MwLWNhMDUtNGJkMy05M2Y3LTIzMDc1MDI4NDkyM182RkQ0MTBGMUUwMzhCMTFGRjNDMjQyRTA4QTcyMjU4RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNjA1L2JkMDI4ODQzLWE3OWMtNGQ2NS05MGIwLTIzMjEyYzQ5ZThhZl82MjQwMEQyODFGNzE1RDQ4Mzk5NUMyREQwNTFBMzBBOS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 349000,
                'gia_khuyen_mai'          => 159000,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Váy 2 Dây Xẻ Tà Vạt Trước',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Xẻ Tà Vạt Trước'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYwNjAzL2IyYjA2YWQxLTk0OWEtNDVmOS1iNGE2LTM4Mjc2N2YzMzgxYV8zRjhCNjlBNDg5RjVGMDVBMjlCM0VERkNCM0I0QTI0OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYwNjAzLzQzNjM2YjhmLTA2ZjQtNDc3Yy05OTdkLTVkZTVmNGQ3ZDY1Y19GQTc5QkQ4MDZGNjBCMzhEQUEyMjI3OUU3Njc3QzI2MC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYwNjAzLzhjZDgxZWU4LTI0ZTItNDFiMy1hNTZlLWQwMTExOTZmMDNjN19FNUIwQzM1NEQxQTY4ODI0OEVEQ0Q0NDE3NDdFRThDMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYwNjAzL2FmMzA2NzNiLWQ4NzItNDE5MS04MmJmLWIxYjc0MDQ2MGE2OF9DQzY4Qzc1MjU2MjQ1NTI4MzgxOEYwMDBFMUQ0MkM1Qy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYwNjAzLzg2NTIyZDEwLWY0ZjQtNGFkZS05ZDE0LThlYTQ3Yjk0NDEwMV80N0U3NTI5QzRDRUU2NEI4MTg5NzE0QTU1NkY2NTk1MS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 315000,
                'gia_khuyen_mai'          => 99000,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy 2 Dây Dáng Dài Xẻ Tà',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Dáng Dài Xẻ Tà'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYzMDAyLzFlNjE1MDNiLWY2ZjktNDFhNS04ZWMwLWNjMjZjZDdiNDMzYl9EOUYxQUZFMkNCMjM3NDUxNTFCNjQwNEEwRkNEMzJBNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYzMDAyLzdkZTIxZTE0LWZhNmMtNDYwOC1hNjE2LTk3ZjA0NDI5NDA2YV9FM0UwODc4NkEzRUU5RjczN0E5NEEwQUMyQUI2OTJDNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYzMDAyLzk1MjhlZWVhLTE2MGYtNGUxNi04OWFjLWJkOTViMjU2NzNiZF9DRjBBNjZFNzc5RjA2RDM1MDMwNUMyRDY3OTZCNEM4QS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYzMDAyLzJjYjYxOTc2LWU4ZmEtNDZkMi1hNWM2LTJmMmYwM2E4MmVlM184MjAxMzdFMzMwOUU4NDlENDVCRjM3RTcxNTJFRUY0NC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdWRFVGTUYzMDAyLzVlYzIwZTVjLTEzMjMtNDVjMy04OGEzLWQ4MmIwNWIyM2FhNF9BMDg5REEyREE3MjA1QjU5NkVDM0I5NjRCMTg0OTFDNi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => 179000,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy 2 Dây Bên Tà Chéo Xếp Ly Dưới',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Bên Tà Chéo Xếp Ly Dưới'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVWRFVGTUYxNjAxLzVjZmNmMmEzLWVmMWItNDA3ZC04ODhkLTA5N2IxOTJjNGQ3OV80RjJGOUJFQjdENDk5NUNCOERCNjY2MTU2RkRCMUNCQi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVWRFVGTUYxNjAxL2FiNmMyYWFjLTRlZmYtNGI2NC05OGExLWZmMGMwMmRkOGE5NV9GNzkwRjNDMjVBRDM5MzUyODE4M0U4QkQwRUQwRENBMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVWRFVGTUYxNjAxLzYwNmMyODVmLWNjMTUtNDU4MC1iZjkxLTM2MDZhMjAxZTZmNV8yQkE2QzVDQ0VDMEEyRUZCMjhGMzNDRTA1ODI0QjVGRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVWRFVGTUYxNjAxLzk5YjM3Yjc0LTc3MTUtNGIxNS1iMmFjLTdmYWY5MTY1MWUyMl8wN0Q2M0REMTg5RDhGRDFFQUVCQTYwMTU3Qzk5OTMxMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDVWRFVGTUYxNjAxLzAzMjRmNWFlLTVlOWQtNGJkYy04MWIwLTY3Y2ViNDIzY2I5OF82RDdGNEFERkU0RTZFRDA3OEQ5M0U1RjAxOTRFOEUwOS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => 59000,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Cổ Sen Đính Nút',
                'slug_san_pham'           => Str::slug('Váy Polo Cổ Sen Đính Nút'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFU1MzYwNzAxLzUyZTcxYTZkLWZlZjAtNGJmYS05MWUyLTBjMzQ3ODIzM2IyM181NTk5MzBGOEQyNjdDRTRGRTVGMzc4MURDREM0N0IwNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFU1MzYwNzAxLzg5YTJiOGRkLTA2MTktNDBhZC05ZGFkLWZmYzYzZTNiMWYwN18xMjhGNkQ3MzkxRUY5MjI1RTU5OUZFMDY5NjczMzk3Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFU1MzYwNzAxLzBmYjE1Y2E1LWI2YjUtNGQ2Ni1hNGUzLTk1YzhmYzZkNTUwZF9CRTE2MEZDN0Y4QkMyMEJBOUJBNzA2ODY2NzJBNTYzNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFU1MzYwNzAxLzk5NTViMjc1LWRmYzEtNGViYi04MWUwLWQwMmFiZTQxMmM5NF84QzJDNTgyOTVFN0I4RDhFRjFCMzFEODhDMDlENDFBQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFU1MzYwNzAxLzEyOTAzNWZiLWU0NjAtNGMyYi1iMGIyLWZlZDc0YjNjMjIzNF8yMTBBMDg3N0MwRDhDRTkzQzAxMTJCMjQ0QTAxQTJERS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 185000,
                'gia_khuyen_mai'          => 59000,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Nữ Phối Màu Ngực',
                'slug_san_pham'           => Str::slug('Váy Polo Nữ Phối Màu Ngực'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNzAxLzA2MGZjYTYyLTdmNmYtNDRjZi1iZDYyLWZiNzAyODE3M2UwMl9FNDY5OTMxRDFBMUU2NjJEOUVFNDIxRUUwRTkwOEMzMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNzAxLzA2NTZlMDI2LWQ0MjItNGUyZS05NDcxLTZiOTY4Zjg2Y2ZmNl83M0RGMTQzNDg5RjMxMUFGODgzRjQzRDM3M0JEMjg1OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNzAxLzMyYjIzMjc4LTc1MGQtNDQwNC05YjJmLWU4NjUxMDc0YmI5N18wRjhGRUY2NEYwOEY1RTI2NjIxM0I2MDMzNkNCRTBGQS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYxNzAxL2Q1YzZlYjBkLThlN2QtNGNiNy05MzkzLWRkOGM4NDE3NzUxZV9EQkVCOEY3NEYxOTdBRUFCNjlDNzM1MzVFRDA4NzFCMi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => 25000,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Dáng Chữ A 3 Nút',
                'slug_san_pham'           => Str::slug('Váy Polo Dáng Chữ A 3 Nút'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYwNTAxLzIzYTVlYzkxLTkzZWEtNGRjYS1hNmRjLTFlMGI4MzI5Zjk5N19BQUQwMUQzMDE4RTQzNEZGQTJFOEE4MDAzM0QyM0ZFNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYwNTAxLzBiMDBlYTY5LTUzMjUtNDIyZC1iNDMzLTYwOTk0MjM4MTM4NV80MzhFMkM0QjlGNkNCMDJBNEJGNzk2NTIzQTgwRTQ0NC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYwNTAxLzEyYzZmZjFmLWQzMmMtNGUxNC04ZjRhLTkxMTAyYTYzODIyY18wQTE3NTY5RDY0QkQ2OTE0QjcxNDVBMENCQTVBQUNCNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYwNTAxLzkwM2Q4NTk4LTMyY2EtNGYzZC05OWNkLTU0Mjc0YTU3NGNkYl9DMjg5MzI5RkEwQkUxQzM0QUU3QkQ0MjI4QjJGNDgxRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFWRFVGTUYwNTAxLzQ1ZDViNmJkLWVmYTYtNGU2My04N2QzLTk0NWEwZjg1Yjg4NV9GNEExQjE0ODQ1Rjc1NTE5N0I4NTc4NDMzRjY2OEFDNC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => 199000,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Nữ Tay Ngắn Bông Hoa',
                'slug_san_pham'           => Str::slug('Áo Thun Nữ Tay Ngắn Bông Hoa'),
                'hinh_anh'                => '',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Chú Mèo',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Chú Mèo'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDNBVFU2ODkwNjA1Lzc0NDUxY2U5LWVlMGEtNDM5Yy1hN2QwLWUzZjY0NTlkYWExOF9BNTFBQ0JEMDA1NzNFN0M5REU0MjkwRDI5N0UzMDRDMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDNBVFU2ODkwNjA1LzVjOTJkZWVhLTViYTQtNDYzZi1hMDA2LWI5YmZiN2NmMDg0Ml8wOTY4OEU1QUNCMjlDNzA2Rjk1MUMyRTdGRjJFOUNDMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDNBVFU2ODkwNjA1L2ZiMDM5YWNiLWUyMzEtNDg2ZS1hN2YxLTBmOTBjOTMxODM4MV8yRjRFMDIzRUEyNjYyNDM3Njk1ODE0MzU0RTE2RDAzQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDNBVFU2ODkwNjA1Lzg3MGQyMTM5LTg2NGEtNDJhNC1hOTAyLTcyY2ZmM2VmOWU5YV8yRDA1MkNFNzMwNDY1QkQ1QkQ3QUFDN0I0OEM3Mzk2Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDNBVFU2ODkwNjA1L2FjNzAwM2E4LTI3MjgtNDI4Ny1iZWU4LWRiMWI2NDVjZDRmNV9DNTA3NzFBMzZCMDA3NUUzMThEQkY1N0Q1Qzg2ODg5Mi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Nữ Tay Ngắn In Chữ You Are Loved',
                'slug_san_pham'           => Str::slug('Áo Thun Nữ Tay Ngắn In Chữ You Are Loved'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBVFU1MzYwMzAxL2E5ZDk0ZjhlLTcwYjgtNDY1Mi1hOGViLTViZTgzYTNjMzBlYl80OUIzQ0VFMkJDNTZFQjUwQTNFQzU2NkZGNTQ2OUQ2MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBVFU1MzYwMzAxL2FhY2E2MjM0LWE0NGYtNGRjNS05OGFmLTMwYzdiYzQ1YjNhMF9DQjQ5MDk1Q0ZFNzAzNDAxMDdEODE1MkZDRTA2OTY0My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBVFU1MzYwMzAxLzg4MTMyOWMyLWJmYjMtNGQ3Ni1iZjA0LWNjNWI3MWFkY2JmYl80REU4QTE0ODkxNEJBMTcxQjdGOEMzQzA0MUU3NEE2Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBVFU1MzYwMzAxL2Y5YTNkOThmLWQ0NjktNDRjYS04ZWExLTVjYWUyZjM4NzQ2YV8xODlBMDRDQUU2MEE3OUQ0MTBGNjdDNTcyODU1OTU3Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBVFU1MzYwMzAxLzI0M2FhMmYzLTM4OGQtNDQ0My05ZDUzLWI5MWYyOTdkOTQ5YV9EN0Y4QUY5RkQzODVFQzkyQkVDMEQ5NjVGQzk0MzQxNS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 100000,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Sơ Mi Nữ Tay Ngắn Cổ Vest Màu Trơn',
                'slug_san_pham'           => Str::slug('Sơ Mi Nữ Tay Ngắn Cổ Vest Màu Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdBU1VGTUYyODAxLzQzMDM4YTFlLTNhMGYtNDRhNS05MzE4LTliOGNhMWFlNjRhOF82NjU4MzM1NENFOUQ2NjUwRjc4QTA2QjE3NzQ2MjBCQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdBU1VGTUYyODAxLzYwY2Q1ZTZiLTIwNDMtNGJlOC1hNjhiLWRmMjVkMmIxYjRmM182NzBDNDQzQjFGRkM1NjFGMDA1NjMyNjIxNTU5NTYzMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdBU1VGTUYyODAxLzg1ZDE3NGQ0LTYwYjctNDc0OC04NjJkLTdiMGNlMGM2ZWUwZF80RTAyMzIyODcxMkJERDE0NUM3NEM2RUNERkZCRTNBRC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdBU1VGTUYyODAxLzUyMGYzYjgyLTE4YzYtNDQwYS1iOWRmLTFhYTNhZTZjMmMzYl9FMEYyOTdCNjdFQzBEMjYzQ0U0MDVEQ0EyMDU4QTI5My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDdBU1VGTUYyODAxLzJlNGU5ZWYxLWQ5MDMtNDZjNS04ZWQwLWMzOTYzZGY2MmQ1M183NzRCNDk4RDBGN0NDQzg5M0VGQjIwNzA5ODE0NDkyMy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 55000,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Lụa Tay Dài',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Lụa Tay Dài'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxMjAxLzFmMTVjYzczLTA2ZjAtNGIwOC05M2RiLTljZDVhYWI5ZWQ3MF85OUNGNjY1NzQ2QkRGMzY0OUUxMkRFMzQ5NTRCRUE3MS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxMjAxL2I5MDlhY2RlLTYwOGQtNDkwYS05M2Y1LTZlOTQ3ZjNkMjQ3Y18yRTE3NkZFODc5OEFCNENGODQxQjhDM0MyNDM2NThDMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxMjAxL2I5Nzk0NmEzLTYzMGQtNGQ0Yi05ZTNiLTVkYjA2ODMxOTk4Y184QjY4ODZBRTBERDMwNEUzMDk3MkNFMUJDQzcxMzkyNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxMjAxLzFlZWMxYjIyLThkZjUtNDc2YS04NmYyLTRhM2UyZGY0ZjZkYl9GRTczQjkyMkY5OTg0NDc1RjcxRTc2M0ExNDU2RDNCNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxMjAxLzI0ZTg0YjRiLWYyNTktNDMwMS1iMjczLWEwZDI5ZDMyMjY5OF80MDhEMjVCQzE3OEJEMENBOEMxNjExNTREQzE0RkYzQi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 55000,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Nữ Tay Dài Phối Bèo',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nữ Tay Dài Phối Bèo'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxNDAxL2U1MjJlNTY3LTIxZmQtNDAwYS1hZWVmLTBkNzg5Njk2ODcyYV8wM0UwRDQ4MEQxODhDMDVBRjVBNTREMUM4RkI0Nzg2OC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxNDAxL2M1NjYyMmUwLWNhN2QtNGQ3OC1iYmQyLTBkZGQ2MzRkOTViZV9DMTE5RDI5MUM1NjVFOTRCNEE5MzNFODM0NEUwNjg4Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxNDAxLzY4ZDM1ZDJjLTJjZmYtNDU0Yy05MmVlLTk5NmZmODE5NzUzZl8xNkM1NUFFQTRCMUZGRjBBNkRGN0MwODQwMERCMzdFMy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxNDAxL2Y5YjNjNjFmLWJhMzgtNDQ1Zi04ZDZlLWZkMTFjMDQxYTdkZV83RUY1QjAxRTNFOUVBMTM3QjE4NTU2QkYxQkU0M0VDMS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTJBU1VGTUYxNDAxLzZkMjZmYjcwLTcxNGEtNDU4Yy1iZTkwLTE2ZTc3NjllODY5ZV9DNTM2QkJDQzQwM0I5NDNCQkFFNEQ2MEVGRTIzQjhBNS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 209000,
                'gia_khuyen_mai'          => 10000,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Kiểu Xốp Tay Dài Cổ Vuông',
                'slug_san_pham'           => Str::slug('Áo Kiểu Xốp Tay Dài Cổ Vuông'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBS1VGTUYyOTAxLzQ4ZGVmZmIzLTA0MjgtNDIyNy04NDBiLWVhN2Y4ODhjYTkyYl84QTdDMjE3NkI2Q0NGQTFCNjU5QURFMTBEMTA1NkFFNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBS1VGTUYyOTAxLzQ4ZGVmZmIzLTA0MjgtNDIyNy04NDBiLWVhN2Y4ODhjYTkyYl84QTdDMjE3NkI2Q0NGQTFCNjU5QURFMTBEMTA1NkFFNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBS1VGTUYyOTAxLzkyMzg3NDAyLTU1N2YtNGU2Yy1iMTg1LTQ1ZjE3YzYyYWEzOV8xNkE5QUM0QTZFQUUyRjAyODJBNTVCRUE1MzBFNEZDRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBS1VGTUYyOTAxLzkyMzg3NDAyLTU1N2YtNGU2Yy1iMTg1LTQ1ZjE3YzYyYWEzOV8xNkE5QUM0QTZFQUUyRjAyODJBNTVCRUE1MzBFNEZDRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTFBS1VGTUYyOTAxL2E1ZGJiOGNhLTUwMWQtNDBlOS04ZWQ1LWRjYTkxMTA0YzZlNV8xNTY5ODlBQUYyODNGNjM3NjAyRDEzQkUxMDUwMERCRS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Kiểu Cổ Tròn Đính Nơ',
                'slug_san_pham'           => Str::slug('Áo Kiểu Cổ Tròn Đính Nơ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBS1VGTUYxNTAxL2M5YjBmNDM5LTFiMzctNDJjNy1iZjE2LTZjYzZkZGE0OTY4YV9FQUI0QzczRERDRjVFQkE4MTQ5QTVEQjhBRDI5MzY0OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBS1VGTUYxNTAxL2M5YjBmNDM5LTFiMzctNDJjNy1iZjE2LTZjYzZkZGE0OTY4YV9FQUI0QzczRERDRjVFQkE4MTQ5QTVEQjhBRDI5MzY0OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBS1VGTUYxNTAxLzk5NzRkOWJhLTBmYzUtNGE5NC1hZGNlLTNlNTM4MWFlMGQ5Zl85NUY5RTE1N0UxNTkyNjg2OEY0Mzk2MEY5MUYwMDVGNC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBS1VGTUYxNTAxLzg4Mzk5NTE4LTgyYmYtNDRjMS04ZTQ1LWIyNDM3MjdmY2ZmYl8zOTREMTcyNEU5NEE2NTMyREI5QzNEMDQwRjQyRTRCNS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJBS1VGTUYxNTAxLzg4Mzk5NTE4LTgyYmYtNDRjMS04ZTQ1LWIyNDM3MjdmY2ZmYl8zOTREMTcyNEU5NEE2NTMyREI5QzNEMDQwRjQyRTRCNS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => 40000,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Voan Tay Dài',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Voan Tay Dài'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU1VGTUYyNzAxLzQ2MmYyZWEyLTA2MzUtNGMwMy05YTNmLTc1NDlmOTJhNzQzOV9FREFERUZCOThFMzg1RUI5Q0U4MTVCNEM1RTM1MzM5RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU1VGTUYyNzAxLzE3MDM1NzQyLWQ2ZGYtNGFmNC1hNDllLTFhNjMwZTdjNWI3MF9BMzk2RTZDREU0MzZCRTA0OUQzQUNEOUEwMTE1MTU4Ny5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU1VGTUYyNzAxLzFjMWQ2ZWIwLTY2MjEtNGE4Ny04NjI2LTJhOGY0ODU4YzFmOF8yRDQzRUQ4QTQ0NEZGNzNBN0Q0MDFDMjkxMEU1MzgwNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU1VGTUYyNzAxLzUwZGVkZDlhLTI1ZjctNDg5MC05MWMyLTVmMDYzNDY2ZDRmN19DQTBFRDIxMjA4NzBBQTlDNThCQ0U1MERCRDJBQThEQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBBU1VGTUYyNzAxLzY5NWI2ZDhiLTI4YjktNGQ3Yy1hNjM1LWY4ZjQ0MDc4ZjJkMF83RTZEQjVFM0E3MkM5NDhGQ0Q3NDY0Njk2QzA1QkUwMi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 175000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Jeans Nữ Ống Loe Đường Lai Giữa',
                'slug_san_pham'           => Str::slug('Quần Jeans Nữ Ống Loe Đường Lai Giữa'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFRSlU1MzYwNzAxL2YzZDcxMmNmLTU4OGQtNDlkYi1iYzY4LWJmMzc5OTY0Nzc4Yl8xMjhCNjdDODJDODQwNERCQTAzMEQ1MTMzRTdGQkE1Ni5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFRSlU1MzYwNzAxLzZjN2EwYjg5LTc3YWQtNDE1NC04M2E2LTlkNzUwMTI0YzM1Yl80RkY0N0MwQjM4QzM4QjJDMEI2ODlCREZFN0I5MkQ1OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFRSlU1MzYwNzAxLzg3NzJjNzFkLTNkZTktNDRiYi04M2FiLTE2ZGVjMjNjYmFjMF9GQjc0MDE1MTczNzMzMjI5ODM2MDQ5NTgxNEIwRjIyMC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFRSlU1MzYwNzAxLzhjNzY2NTVkLTNiMmQtNGM0MS1hNGVjLTRjMTQ4NTEyNmRiOF9DNDYzN0ZBNDIwOUIyNDFEQjBGNTI2RDQzRDVCMEU4Ni5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFRSlU1MzYwNzAxL2RmMTQwZDcxLWM0MDgtNGI1ZS1iNzA3LWEzMjAzMzRmN2MxY180NzM4Qjk1RDc4M0IwMjFDNjRCNTI3QkRGNDYyQkJFNy5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 199000,
                'gia_khuyen_mai'          => 30000,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Baggy Jeans Gấp Sườn',
                'slug_san_pham'           => Str::slug('Quần Baggy Jeans Gấp Sườn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRQlU1MzYxOTAxLzM0ODhhNDEzLTFjNjMtNDNiMC04NzE3LWZiZjM5MjUwMjkyOF9DRjZEQzM0MzVDNEVCQUE5MkZBODNCREM2NjdDNjM0QS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRQlU1MzYxOTAxLzA1YjdkOTIxLTI4MmYtNDI1Yi05N2ZmLWRiYjc4ODM3NGQ2Y185ODVBNDhDNDQ0OUI3MTU5NEI4QjA5RTRBQkYzQjI2OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRQlU1MzYxOTAxLzIwYmY4NjdkLWFlODgtNDRlNy04NzdkLTdhZDI0ZmZmMzkwZV80RjY5RjMzRDlENzE0RkVDMTVCOENCODU2OUNBQjY0OC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRQlU1MzYxOTAxL2VhNDFkNTdiLTUyNWUtNDZjNi1hZmU5LWIxZjllMGEyNWU1ZV9DMTdGQTgzNkEyMjM1REVGRUI4Mjk3REVFRDQzRjY5Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMTBRQlU1MzYxOTAxLzRlMDIxYzVmLTI1MGMtNDE4OS1iNWMzLTcwZTc2MGVlZTIzMF84QzlGNjBFNDFENTM5QUUyM0ZERjE3RkMwMzIwRkQ4NC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 239000,
                'gia_khuyen_mai'          => 60000,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Nữ Ống Suông 2 Túi Trước',
                'slug_san_pham'           => Str::slug('Quần Jeans Nữ Ống Suông 2 Túi Trước'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRSlU1MzYzMTAzLzZiOTQwMWNmLWRlMTMtNDExOC05MmI3LTBiZDQ0MzMxNzBkNl9CN0QwQTIyNTVBRDU2RDVGRTg0NzA5Qjg3N0ZGRDA0NS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRSlU1MzYzMTAzLzg5NGExM2ZkLTE3ODAtNDU4Ny1iMDM2LWNjNjUxZjg5MDNkOF8yNUQxQ0IzMzg1MThFQkEzQjM4NTg5Qzc1RTNDRTVCRS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRSlU1MzYzMTAzLzk5MmE0ZWUzLTIzZmItNDRmOC1iOTFjLWJkZDE3NDE2ZmI2ZV84RTdBOTg4OEJCNjQ4NzNDNEFDMDA0RERGMzlGNUI3OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRSlU1MzYzMTAzL2ViMTJkNmU4LTJmMDktNGNlYS1iZmNiLWI5MDIwMTM2MzQwMV9FNDg0QkI1RUE5NURDQkVENzBFODJENjkyRDAxMTFEQS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDhRSlU1MzYzMTAzLzdhYTgwZWU4LWEyNzYtNGZiMS04YWUxLTU0N2M5ODdkYWJmMV8yNUU3QkY1RkJCQUM4RDY4NTI2MTA5QTFBQjczQjZCQS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Baggy Gấu Bằng',
                'slug_san_pham'           => Str::slug('Quần Baggy Gấu Bằng'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDVRQlU1ODExMjAxL2Y3MjczNWYzLWNhZDMtNDBkNS1iN2Y3LWM0M2Q4NGM2ZDY0Yl8zNjk3RjUxOEI2ODQ4RkVFNkU5NTc0QkQwQzdDODUwOC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDVRQlU1ODExMjAxLzA4Zjg5NDhkLTUyOGItNDhiNy04OGQ0LWY3YzczNzgwNWQ3NV8zOUJCQUQ1MkFERTUyQUJENDI1NzhCM0U2ODNGNTdGQS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDVRQlU1ODExMjAxL2JmNTNjZjRmLWFmNzUtNDJmNi1iYWM2LThjOWY3YTc1Mzk2NF83MkEyNjNBMDhCRTUyOTgwRjJCOEI0QUYwN0QxOUQ1Ri5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDVRQlU1ODExMjAxL2ExYWE1NjBmLTgwM2ItNDk2NC05OThhLTFhY2FkMGJhMzI3NV8wMEUxQzQzQTdBRDk5REREOTQ0OEQ3NzYxNTY4Q0Q4OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDVRQlU1ODExMjAxLzI5NzVhZTExLWZiNGItNDNhOC05YThiLTdlNDE0MWQ0ZmJkN184NDMyQjEwRDIxQzVEQzEzMDU5Mjc5QTMxQjE4MEY3OS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 225000,
                'gia_khuyen_mai'          => 35000,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Tây Baggy Gấu Lệch',
                'slug_san_pham'           => Str::slug('Quần Tây Baggy Gấu Lệch'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDlRQlU1ODEwNzA3LzgyYTMwY2QzLWEzNjktNDcwYi1hMGMxLTU2ZWU5OGFlMTNhYV9GNjBFMkM0Nzc2MUQzOUI4OTFDNEYyQkZGQjNDNDVGOS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDlRQlU1ODEwNzA3LzY1ODM0YTgzLTNlZDQtNDA5My1hYzc0LTg4OWFhOGYzZTE4Zl9BRjY5QkJBRTE1NkI0MTM2RDlCMDg5RDRGRTM0OTg1QS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDlRQlU1ODEwNzA3LzhjYmZlMzNkLTY3Y2QtNDczYS1iNWU2LWFlZmI2ZDQwN2IwYl9FNDYzRTI3RjNDODdFMEU5MEEzQ0I1OTQzMDMzMzE3OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDlRQlU1ODEwNzA3L2JmNGQ3MmQyLTkyOTItNDI0Mi05NmRkLWNlNmJlYzZmMzllOV85NzJGNjI2ODBBMkQ4ODI3NzJDMjZENEU4OEY5RUE2RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIxMDlRQlU1ODEwNzA3L2RiMjYxMjlkLWMyZWMtNDgwNy05OGE4LWVmODkwOTUyYWM0NV9EMjE5RThFNTI2MTAxNEE4RkRGNTkxQzk1QkUwQzREMi5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 145000,
                'gia_khuyen_mai'          => 20000,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Tây Ống Rộng 1 Khuy',
                'slug_san_pham'           => Str::slug('Quần Tây Ống Rộng 1 Khuy'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRQlU1ODExODAxL2Q2NDIyODVlLWYzNjItNGYwMy1iNjgzLTYxYjgzZTZmOWExMl9CMjI3RjlBN0Q1NTZGQTU5NEI2ODJFRDlGOERDMjEzQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRQlU1ODExODAxL2Q2NDIyODVlLWYzNjItNGYwMy1iNjgzLTYxYjgzZTZmOWExMl9CMjI3RjlBN0Q1NTZGQTU5NEI2ODJFRDlGOERDMjEzQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRQlU1ODExODAxLzQ5NDVhZDU2LTUxOTctNGFkMC1iYTYzLTdhNGUwYTg0ODRlNV8yQUExMDcyNDAwNURERjEyOUJFRjAzNEM1MzUzNTczQy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRQlU1ODExODAxLzg4OTZmZWFiLWRlOGUtNGRiYy05ZDI0LWE5ZTc5ZGJhMDgzM184OEFBMDJERjVDRjUxODkyQjdCMUVBOTk3NzY1NTA3My5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIyMDRRQlU1ODExODAxLzVlOGNmM2YyLWYzZWItNDdmZS1iNzllLTFmNDQ0YTM5Nzg5MV9CMzk0OEY2Q0U1N0Q3RjM2MzExQTUwNTE1M0E1QUU2OC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 269000,
                'gia_khuyen_mai'          => 70000,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Baggy Kaki Ống Suông',
                'slug_san_pham'           => Str::slug('Quần Baggy Kaki Ống Suông'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJRQlU1ODEyNTAxL2NkYWM2YWUzLWVjMjQtNDNhZC1iOTZiLWEyZTQ0NzMxOTQyM180MzI0NjJGNDk1MDQ2NTMwNkMxMjNCRTE2MUQwMjNDMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJRQlU1ODEyNTAxL2JlZGJhNTVkLTg0NmEtNDdlMC05ZTI0LTA4NDY0NTA2YzA4OV85ODE4QTJDMTgyMjIxOEI4MDgzMTI2NUM0QkU4RUM1RC5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJRQlU1ODEyNTAxL2I3ODVhZmYwLWUyYWEtNDRmNi05MjM3LTdjNDI4MTZkZDg1Yl80RkQwOUMyNTYwMTIzRDIzOEQ4MjA1NUI0MUQ3ODQ4OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJRQlU1ODEyNTAxL2Q0Yjg3YWUwLWZkMGYtNDA3Zi1hMGFkLTkzMDFmNmNhMTFlMF9BQUZFMThBQkFBMzQwMjA2ODE2OTkyQUFBNTI2MEQyNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJRQlU1ODEyNTAxLzY1NDAxNjA2LWM4MDctNGYwZi1hMzNlLWUwNTU3Y2Q5NzQxMF9EMzU0QjRCRjg4NzVEMDQ5NzlCMkNFQTU0RDlCQ0MxOS5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => 50000,
                'id_chuyen_muc'           => '27',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Baggy Jean 2 Túi Nắp Hộp',
                'slug_san_pham'           => Str::slug('Quần Baggy Jean 2 Túi Nắp Hộp'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJCSlU1MzYxMTAxLzMxODNiZTRlLTgxNDMtNDI5OS05ZGVlLTg4NjRiYTZjOGNlNl82RUMxN0IyQjJCODk3Mzc5OEUwQzBFRENDQTk1QjQ3OS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJCSlU1MzYxMTAxLzM2ZmVjMGI0LTI1YTMtNDgzNC04ZTQwLWFkNTllZjM4NDExZF9BNzdGNjU3NEJFNzQzMjgyOTlENzI2RkUyOUM4NzQ3QS5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJCSlU1MzYxMTAxLzQwN2QzYjI1LWRmNGUtNGI5NC04ZTFlLWE4YzVkZWI0YzJhNF8yNkVEQjI5RjhCRkQyM0JGNDAzRDgzQzQ1OUJERkNFNy5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJCSlU1MzYxMTAxLzI5ZTZmOGU2LTc1OTAtNDQ5Ny1hMWRlLTMzYmZiNWNmNmQ0Nl9BNEUzRDQyM0YxNDBEQUZBRjYwQTA1NUU3QTA0OTYzMi5qcGc1,https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDJCSlU1MzYxMTAxLzZmOGYxYjE3LTE4YzctNDBlNy1hMDYwLTBkOWZkYjM2NDZkMF9GNTFBQTg0NDM4MkREMzdGNTNBMzIwMTc4NjRDNDE1NC5qcGc1',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => 30000,
                'id_chuyen_muc'           => '27',
                'trang_thai'              => '1',
            ],



        ]);
    }
}
