@extends('client.master')
@section('noi_dung')
    @include('client.banner')
    @include('client.ship')
    @include('client.8_san_pham')
    @include('client.slide')
    @include('client.best_sale')
@endsection
@section('js')
@endsection
